name: CI

on:
  push:
    branches:
      - develop

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0'

      - name: Restore dependencies
        run: dotnet restore backend/backend.sln

      - name: Build solution
        run: dotnet build backend/backend.sln --configuration Release

      - name: Run backend tests
        run: dotnet test backend/tests/tests.csproj --configuration Release

  frontend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use your desired Node version

      - name: Install Angular CLI globally
        run: npm install -g @angular/cli

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Run frontend tests
        run: |
          cd frontend
          ng test --watch=false --browsers=ChromeHeadless
