name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
      MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
      MYSQL_USER: ${{ secrets.MYSQL_USER }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      APP_DOMAIN: ${{ secrets.APP_DOMAIN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: SSH into OVH VPS and deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /opt/pollitic.eu
            sudo git pull origin main
            echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" | sudo tee -a .env
            echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" | sudo tee -a .env
            echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" | sudo tee -a .env
            echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" | sudo tee -a .env
            sudo docker-compose down
            sudo docker-compose up --build -d
