name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
      MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
      MYSQL_USER: ${{ secrets.MYSQL_USER }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      APP_DOMAIN: ${{ secrets.APP_DOMAIN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: SSH into OVH VPS and deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /opt/pollitic.eu
            # Write the environment variables to a .env file in the project directory
            cat > .env <<EOF
            MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE=${MYSQL_DATABASE}
            MYSQL_USER=${MYSQL_USER}
            MYSQL_PASSWORD=${MYSQL_PASSWORD}
            APP_DOMAIN=${APP_DOMAIN}
            EOF

            # For debugging, you could echo the .env file (remove or mask sensitive info in production)
            # cat .env

            sudo git pull origin main
            sudo docker-compose down
            # Use sudo -E to preserve the environment (if you still need it) but .env will be read automatically
            sudo docker-compose up --build -d
