name: Integration Tests

on:
  push:
    branches:
      - develop

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    env:
      MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
      MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
      MYSQL_USER: ${{ secrets.MYSQL_USER }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      APP_DOMAIN: ${{ secrets.APP_DOMAIN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        working-directory: ./backend
        run: dotnet restore

      - name: Build
        working-directory: ./backend
        run: dotnet build --configuration Release

      - name: Run Tests
        run: dotnet test ./Backend.IntegrationTests/Backend.IntegrationTests.csproj --configuration Release --no-build

  frontend-tests:
    runs-on: ubuntu-latest
    needs: backend-tests
    env:
      APP_DOMAIN: ${{ secrets.APP_DOMAIN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Start Frontend Server
        working-directory: ./frontend
        run: nohup npm run start &

      - name: Wait for Frontend to be Ready
        run: sleep 15

      - name: Run Cypress E2E Tests
        working-directory: ./frontend
        run: npm run cypress:run
